#!/usr/bin/env awk
BEGIN {
    print "module type PLUG = "
    print "  sig"
}
{
    print;
}
END {
    print "  end"
    print ";;"
    print "let __" module "__plugin_ref = ref None;;"
    print "let get_" module "_plugin () : (module PLUG)  = match !__" module "__plugin_ref with | Some s -> s | None -> failwith \"No plugin loaded\""
}
