#!/usr/bin/env awk
BEGIN{
    print "open " moduleName ";;";
}
/val/ {
    print "let " $2 " = fun () -> "
    print "  let module " module " = (val get_" module "_plugin () : PLUG) in"
    print "    (" module "." $2 ")"
}
